""" create access_requests table

Revision ID: 0414ffaa643a
Revises: 9d9c97c6acbc
Create Date: 2025-09-02 12:13:27.110082

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0414ffaa643a'
down_revision = '9d9c97c6acbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_requests',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('app_id', sa.Integer(), nullable=False),
                    sa.Column('user_auth_guid', sa.String(), nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.String(length=50), nullable=True),
                    sa.Column('updated_by', sa.String(length=50), nullable=True),
                    sa.ForeignKeyConstraint(['app_id'], ['applications.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_requests')
    # ### end Alembic commands ###
