""" Add email_queue table

Revision ID: e2f33ae4b62a
Revises: 0414ffaa643a
Create Date: 2025-09-03 15:01:38.474624

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e2f33ae4b62a'
down_revision = '0414ffaa643a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_queue',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('template_name', sa.String(length=255), nullable=False),
                    sa.Column('status', sa.String(length=50), nullable=False),
                    sa.Column('payload', sa.JSON(), nullable=False),
                    sa.Column('error_message', sa.Text(), nullable=True),
                    sa.Column('sent_at', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_queue')
    # ### end Alembic commands ###
